### ISSUE TITLE
Older versions of your build folder.

### ISSUE THREAD

**Issue by davefes** [nspsck/STM32F411CEU6_BlackPill_Micropython#11]
The only pre-built hex file that I can get to work on these boards was mostly likely from a build you did around 30 Nov 2023.  Unfortunately, I deleted this folder when your new version came out :(

Would you be so kind as to provide a link to the whole "regular version" build folder from around that date.  I can supply my email address if you want.  It is 912,484 bytes for firmware.hex.

I would like to see what is different in all of the new releases that might be causing my UART serial comms problems.

Thank you.

**Comment by davefes** [comment]
Tonight the latest firmware for the WEACTf411CE (base-version) runs my program on the 8MB board.

**Comment by nspsck** [comment]
> The only pre-built hex file that I can get to work on these boards was mostly likely from a build you did around 30 Nov 2023.  Unfortunately, I deleted this folder when your new version came out :(
> 
> Would you be so kind as to provide a link to the whole "regular version" build folder from around that date.  I can supply my email address if you want.  It is 912,484 bytes for firmware.hex.
> 
> I would like to see what is different in all of the new releases that might be causing my UART serial comms problems.
> 
> Thank you.

Hi, sorry, was busy. I usually don't keep the previous version so I don't have it myself.

But it's nice to hear that the latest version works! Hope you are happy with it!
