### ISSUE TITLE
DFU setup in README.md

### ISSUE THREAD

**Issue by davefes** [nspsck/STM32F411CEU6_BlackPill_Micropython#13]
I think there was a comment in the previous README that A9 had to be connected to A10.  I see the comment about A9 at the bottom.

**Comment by nspsck** [comment]
Actually, it states : A10 to GND.

The reason is here: https://www.acheronproject.com/joker_mcus/joker/#:~:text=PA10,general%20input%2Doutput

But I think this was a really old revision problem. If you got something newer, you should not be worrying about this.

**Comment by davefes** [comment]
Correct.  I was actually connecting A9 to A10 to get into DFU mode.  I will try again without any jumper.

Thank you.
