### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by davefes** [nspsck/STM32F411CEU6_BlackPill_Micropython#3]
May I suggest a few additional comments, especially for people not familiar with this board.

Add "Flashing by DFU" as per here https://github.com/mcauser/WEACT_F411CEU6
and deploy.  Also, I have found just connecting A10 to ground seems to work best, at least for "pirated" boards.

Some comments I have used:

> #!/bin/sh
set -x
echo -e -n "\xff" > ff.bin
dfu-util -s :mass-erase:force -a 0 -d 0483:df11 -D ff.bin

To load dfu file
`sudo dfu-util --alt 0 -D firmware.dfu`

The mass erase is from https://github.com/dhylands/upy-examples, I think `To load dfu file` was yours.

**Comment by nspsck** [comment]
Hi,

Thank you for the suggestion and effort to get all these commands! I'll put them after the `How to build` section.

PS. The `To load dfu file` is from the official documentation provided by Micropython. Please view details [here](https://micropython.org/download/NUCLEO_F411RE/).

**Comment by davefes** [comment]
Thank you for the "source" correction.  There has been a lot of activity here recently ;)
