### ISSUE TITLE
BlackPill with 8MHz HSE

### ISSUE THREAD

**Issue by davefes** [nspsck/STM32F411CEU6_BlackPill_Micropython#7]
Would it be as simple as changing the line in mpconfigboard.h:
`#define MICROPY_HW_CLK_PLLM (25)`
to
`#define MICROPY_HW_CLK_PLLM (8)`

I have asked WeACT if they plan to make 8MHz HSE wth 8MB flash.

**Comment by davefes** [comment]
They do not plan to make them.  I asked for the part number for the 8MHz HSE and they said:
`smd3225-4p` so I ordered 10 pcs from Aliexpress.

I asked if the crystal load capacitors C3 and C4 needed changing.  They said `no` but also mentioned 10pF ... I think the originals are 12pF, so a frequency counter may be needed to verify.

**Comment by nspsck** [comment]
> Would it be as simple as changing the line in mpconfigboard.h:
#define MICROPY_HW_CLK_PLLM (25)
to
#define MICROPY_HW_CLK_PLLM (8)

A little more than that, you also have to change the `HSE_VALUE` in ` stm32f4xx_hal_conf_base.h` to, well, you guessed it, `8000000`. Also I am planning to add some more `BOARD_VARIANT`s. Most likely later today. 

> I asked if the crystal load capacitors C3 and C4 needed changing. They said no but also mentioned 10pF ... I think the originals are 12pF, so a frequency counter may be needed to verify.

I think they were just trying to ensure a worst case scenario. I have soldered some flashes (w25q128) onto those without the caps and they worked all fine. Even when I bumped the SPI speed to 48MHz. Haven't tested 60MHz yet. Or, am not really sure if that is tested or not... Will be checking that also later today. CET Timezone btw.

**Comment by davefes** [comment]
HSE load capacitor values define correct oscillator operation and frequency.  As they seemed to have problems with keeping the 25MHz HSE within a reasonable frequency tolerance, the 8MHz HSE capacitor values will probably be quite critical as well.

Thanks for the hint on `HSE_VALUE`

**Comment by davefes** [comment]
Small correction:

> The 8MB version has the advantage to be more stable in terms of dfu-bootloader connectivity

should be `8MHz version`

Thank you for providing updated firmware.

**Comment by nspsck** [comment]
Thanks! Mb.
